# Generated by Django 4.2.4 on 2023-12-07 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0004_remove_baseuser_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custom_User',
            fields=[
                ('C_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=150)),
                ('place', models.CharField(max_length=150)),
                ('age', models.IntegerField()),
                ('vehicle_type', models.CharField(choices=[('Four wheeler', 'Four wheeler'), ('Two wheeler', 'Two wheeler')], max_length=100)),
                ('vehicle_no', models.CharField(max_length=150)),
            ],
        ),
    ]
