# Generated by Django 4.2.4 on 2023-12-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='user_img',
            field=models.ImageField(default='default.jpg', upload_to='user_images/'),
        ),
    ]
