# Generated by Django 4.2.4 on 2023-11-27 04:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_baseuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='^(\\+91[\\-\\s]?)?[0]?(91)?[789]\\d{9}$')]),
        ),
    ]
