# Generated by Django 4.2.4 on 2023-12-06 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_baseuser_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='location',
        ),
    ]
