# Generated by Django 4.2.4 on 2023-11-27 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0003_alter_baseuser_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargingStation',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cmp_name', models.CharField(max_length=255)),
                ('join_request', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
