# Generated by Django 4.2.4 on 2023-11-22 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charging_station', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charging_station',
            name='role',
        ),
    ]
