# Generated by Django 4.2.4 on 2023-10-27 06:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_station', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charging_station',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits long (e.g., 1234567890).', regex='^(\\+91[\\-\\s]?)?[0]?(91)?[789]\\d{9}$')]),
        ),
    ]
