# Generated by Django 4.2.4 on 2023-10-30 05:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_station', '0002_alter_charging_station_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.RegexValidator(regex='^(?=.*[A-Z])(?=.*[\\W_]).{8,}$')])),
            ],
        ),
        migrations.AlterField(
            model_name='charging_station',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='^(\\+91[\\-\\s]?)?[0]?(91)?[789]\\d{9}$')]),
        ),
    ]
