# Generated by Django 4.2.4 on 2023-11-22 06:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_station', '0002_remove_charging_station_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='charging_station',
            name='cmp_name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='charging_station',
            name='phone',
            field=models.CharField(default=None, max_length=10, validators=[django.core.validators.RegexValidator(regex='^(\\+91[\\-\\s]?)?[0]?(91)?[789]\\d{9}$')]),
        ),
    ]
