# Generated by Django 4.2.4 on 2023-11-27 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_station', '0002_rename_chargingstation_charging_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charging_station',
            name='join_request',
            field=models.CharField(choices=[('Reject', 'Reject'), ('Accept', 'Accept')], default='Reject', max_length=60),
        ),
        migrations.AlterField(
            model_name='charging_station',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable')], default='Unavailable', max_length=50),
        ),
    ]
