# Generated by Django 4.2.4 on 2023-10-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_station', '0003_login_alter_charging_station_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charging_station',
            name='place',
        ),
        migrations.AddField(
            model_name='charging_station',
            name='address',
            field=models.TextField(default='Your_Default_Value', max_length=100),
        ),
    ]
