# Generated by Django 4.2.4 on 2023-12-04 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charging_station', '0003_alter_charging_station_join_request_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cs_Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.CharField(max_length=300)),
                ('offer_post_day', models.DateTimeField(auto_now_add=True)),
                ('offer_duration', models.DateField()),
                ('offer_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charging_station.charging_station')),
            ],
        ),
    ]
