# Generated by Django 4.2.4 on 2023-12-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_station', '0004_cs_offers'),
    ]

    operations = [
        migrations.AddField(
            model_name='charging_station',
            name='cs_Img',
            field=models.ImageField(default='default.jpg', upload_to='cs_images/'),
        ),
    ]
