# Generated by Django 4.2.4 on 2023-11-05 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_station', '0004_remove_charging_station_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charging_station',
            name='join_request',
            field=models.CharField(choices=[('Accept', 'Accept'), ('Reject', 'Reject')], default='None', max_length=20),
        ),
    ]
