# Generated by Django 4.2.4 on 2023-12-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_station', '0005_charging_station_cs_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='charging_station',
            name='lat',
            field=models.CharField(default='Nil', max_length=200),
        ),
        migrations.AddField(
            model_name='charging_station',
            name='long',
            field=models.CharField(default='Nil', max_length=200),
        ),
    ]
